import { useState } from 'react';
import type { FormEvent } from 'react';
import { CommerceClient } from './client';
import { useQuery } from './useQuery';
import { AddressForm, ErrorBox, Pagination } from './ui';
import type { AddressBookView, MerchantApplicationView, Page, ProfileView } from './types';
const states = { PENDING: '等待审核', APPROVED: '已批准', REJECTED: '已拒绝', WITHDRAWN: '已撤回' };
export function AuthForms({ client, verifyOnly = false, onVerified }: { client: CommerceClient; verifyOnly?: boolean; onVerified?: () => void }) {
    const [mode, setMode] = useState(verifyOnly ? 'verify' : 'register'), [error, setError] = useState<unknown>(), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
    async function submit(e: FormEvent<HTMLFormElement>) {
        e.preventDefault(); const f = new FormData(e.currentTarget); const body = Object.fromEntries(f.entries());
        const path = ({ register: '/auth/register', verify: '/auth/verify-email', resend: '/auth/verification-request', forgot: '/auth/password-reset/request', reset: '/auth/password-reset/confirm' })[mode];
        if (!path) return;
        setBusy(true); setError(undefined); setNotice('');
        try { await client.request(path, 'POST', body); if(mode==='verify')onVerified?.(); setNotice(mode === 'verify' ? (verifyOnly ? '邮箱已验证并绑定。账户资料已刷新。' : '邮箱已验证，请使用账号和密码登录。') : mode === 'reset' ? '密码已重置，旧会话已撤销。请重新登录。' : '申请已受理。若符合条件，请在本机受保护的模拟邮件目录通过 CLI 取得验证码；系统不会在页面显示验证码，也不会发送真实邮件。'); }
        catch (err) { setError(err); } finally { setBusy(false); }
    }
    return <section className="account-section"><h2>{verifyOnly?'验证新邮箱':'注册与账号恢复'}</h2><div className="filters">{(verifyOnly ? [['verify','验证邮箱'],['resend','重发验证']] : [['register','注册'],['verify','验证邮箱'],['resend','重发验证'],['forgot','忘记密码'],['reset','重置密码']]).map(([v,l]) => <button className={mode===v?'active':'subtle'} key={v} onClick={()=>{setMode(v);setNotice('');setError(undefined);}}>{l}</button>)}</div><form key={mode} onSubmit={submit}><ErrorBox error={error}/>{notice&&<p role="status">{notice}</p>}{mode==='register'&&<label>新账号<input name="username" required pattern="[a-z0-9_.-]{1,80}" maxLength={80}/></label>}<label>邮箱<input name="email" type="email" required maxLength={254}/></label>{['verify','reset'].includes(mode)&&<label>邮件验证码<input name="code" required maxLength={256} autoComplete="one-time-code"/></label>}{['register','reset'].includes(mode)&&<label>新密码<input name={mode==='reset'?'new_password':'password'} type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label>}<button disabled={busy}>提交{busy?'中…':''}</button></form></section>;
}
export function AccountCenter({ client, customer, allowAccountWrites, publicDemo, onPasswordChanged, onIdentityRefresh }: { client: CommerceClient; customer: boolean; allowAccountWrites: boolean; publicDemo: boolean; onPasswordChanged:()=>void; onIdentityRefresh:()=>Promise<void> }) {
    const profile=useQuery<ProfileView>(client,'/account/profile');
    const [error,setError]=useState<unknown>(),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
    async function submit(e:FormEvent<HTMLFormElement>,path:string) { e.preventDefault(); const f=new FormData(e.currentTarget); const body:Record<string,unknown>=Object.fromEntries(f.entries()); if(path!=='/account/password')body.expected_version=profile.data?.version; setError(undefined);setBusy(true);setNotice('');try { await client.request(path,'POST',body); if(path==='/account/password'){onPasswordChanged();return;} if(path==='/account/email')setNotice('绑定申请已受理。请在本机模拟邮件中取得验证码，在登录区验证邮箱；验证前原邮箱仍有效。');else setNotice('资料已保存。');profile.refresh(); }catch(err){setError(err);}finally{setBusy(false);} }
    return <><div className="section-head"><h1>我的账户</h1><button className="subtle" onClick={async()=>{setError(undefined);try{await onIdentityRefresh();profile.refresh();}catch(err){setError(err);}}}>刷新账户与店铺资格</button></div><ErrorBox error={error??profile.error}/>{notice&&<p role="status">{notice}</p>}{profile.data&&<><section className="account-section"><h2>个人资料</h2><p>{profile.data.username} · 邮箱 {profile.data.email??'尚未绑定'} · {profile.data.email_verified?'已验证':'未验证'}</p>{!allowAccountWrites && <p>显示名称：{profile.data.display_name} · 联系电话：{profile.data.phone || "未填写"}</p>}{allowAccountWrites && <form key={profile.data.version} onSubmit={e=>submit(e,'/account/profile')}><label>显示名称<input name="display_name" maxLength={100} defaultValue={profile.data.display_name}/></label><label>联系电话<input name="phone" maxLength={32} defaultValue={profile.data.phone}/></label><button disabled={busy}>保存资料</button></form>}</section>{allowAccountWrites && <><section className="account-section"><h2>绑定邮箱</h2><form onSubmit={e=>submit(e,'/account/email')}><label>新邮箱<input type="email" name="email" required maxLength={254}/></label><label>当前密码<input type="password" name="current_password" required autoComplete="current-password"/></label><button disabled={busy}>申请绑定</button></form><AuthForms client={client} verifyOnly onVerified={profile.refresh}/></section><section className="account-section"><h2>修改密码</h2><p>修改成功会撤销全部会话，请重新登录。</p><form onSubmit={e=>submit(e,'/account/password')}><label>当前密码<input type="password" name="current_password" required autoComplete="current-password"/></label><label>新密码<input type="password" name="new_password" required minLength={12} maxLength={128} autoComplete="new-password"/></label><button disabled={busy}>修改密码并退出</button></form></section></>}</>}{publicDemo&&<p>共享演示账户不开放资料、邮箱、密码或入驻修改。地址簿请只填虚构信息。</p>}{customer&&<><AddressBook client={client}/><Applications client={client} readOnly={!allowAccountWrites}/></>}</>;
}
function AddressBook({client}:{client:CommerceClient}) {
    const q=useQuery<Page<AddressBookView>>(client,'/customer/addresses?limit=20&offset=0'); const [editing,setEditing]=useState<AddressBookView>(),[isDefault,setDefault]=useState(false),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false),[formKey,setFormKey]=useState(0);
    async function write(path:string,body:unknown){setBusy(true);setError(undefined);try{await client.request(path,'POST',body);setEditing(undefined);setDefault(false);setFormKey(n=>n+1);q.refresh();}catch(e){setError(e);}finally{setBusy(false);}}
    return <section className="account-section"><div className="section-head"><h2>地址簿</h2><button className="subtle" onClick={q.refresh}>刷新地址</button></div><p>最多保存 20 条地址；修改不会改变旧订单的收货快照。</p><ErrorBox error={error??q.error}/>{q.data?.items.map(a=><article className="cart-row" key={a.id}><div><strong>{a.address.recipient_name} {a.is_default?'· 默认地址':''}</strong><p>{a.address.region} {a.address.city} {a.address.address_line} · {a.address.phone}</p></div><button className="subtle" disabled={busy} onClick={()=>{setEditing(a);setDefault(a.is_default);setFormKey(n=>n+1);}}>编辑地址</button><button className="subtle" disabled={busy} onClick={()=>write(`/customer/addresses/${a.id}/delete`,{expected_version:a.version})}>删除地址</button></article>)}<h3>{editing?'编辑地址':'添加地址'}</h3><label><input type="checkbox" checked={isDefault} onChange={e=>setDefault(e.target.checked)}/>设为默认地址</label><AddressForm key={formKey} initial={editing?.address} disabled={busy} button={editing?'保存地址':'添加地址'} onSave={address=>write(editing?`/customer/addresses/${editing.id}/edit`:'/customer/addresses',{...(editing?{expected_version:editing.version}:{}),address,is_default:isDefault})}/>{editing&&<button className="subtle" onClick={()=>{setEditing(undefined);setDefault(false);setFormKey(n=>n+1);}}>取消编辑</button>}</section>;
}
export function Applications({client,review=false,readOnly=false}:{client:CommerceClient;review?:boolean;readOnly?:boolean}) {
    const [offset,setOffset]=useState(0),[state,setState]=useState(''),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false);
    const base=review?'/review/merchant-applications':'/customer/merchant-applications'; const q=useQuery<Page<MerchantApplicationView>>(client,`${base}?limit=20&offset=${offset}${review&&state?`&state=${state}`:''}`);
    async function write(path:string,body:unknown){setBusy(true);setError(undefined);try{await client.request(path,'POST',body);q.refresh();}catch(e){setError(e);}finally{setBusy(false);}}
    function apply(e:FormEvent<HTMLFormElement>){e.preventDefault();void write(base,Object.fromEntries(new FormData(e.currentTarget).entries()));}
    return <section className="account-section"><div className="section-head"><h2>{review?'商家入驻审核':'商家入驻与申请历史'}</h2><button className="subtle" onClick={q.refresh}>刷新申请</button></div><ErrorBox error={error??q.error}/>{review?<label>申请状态<select value={state} onChange={e=>{setState(e.target.value);setOffset(0);}}><option value="">全部</option>{Object.entries(states).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>:!readOnly&&<><p>已验证邮箱的客户可以申请店铺；批准后点击“刷新账户与店铺资格”进入店铺工作台。</p><form onSubmit={apply}>{([['shop_name','店铺名称',200],['business_scope','经营范围',500],['contact_name','联系人',100],['contact_phone','联系手机',32],['description','店铺介绍',2000]] as const).map(([name,label,max])=><label key={name}>{label}<input name={name} required maxLength={max}/></label>)}<button disabled={busy}>提交入驻申请</button></form></>}{q.data?.items.map(a=><article className="account-section" key={a.id}><h3>{a.shop_name} · {states[a.state]}</h3><p>{a.business_scope} · {a.contact_name} · {a.contact_phone}</p><p>{a.description}</p>{a.decision_reason&&<p>审核理由：{a.decision_reason}</p>}{a.shop_id&&<p>获批店铺：{a.shop_id}</p>}{a.state==='PENDING'&&!readOnly&&(review?<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void write(`${base}/${a.id}/decision`,{expected_version:a.version,decision:f.get('decision'),reason:f.get('reason')});}}><label>审核决定<select name="decision"><option value="APPROVE">批准</option><option value="REJECT">拒绝</option></select></label><label>审核理由（拒绝时必填）<input name="reason" maxLength={500}/></label><button disabled={busy}>提交审核决定</button></form>:<button disabled={busy} onClick={()=>write(`${base}/${a.id}/withdraw`,{expected_version:a.version})}>撤回申请</button>)}</article>)}{q.data?.items.length===0&&<p>暂无申请。</p>}<Pagination offset={offset} hasMore={q.data?.has_more??false} onChange={setOffset}/></section>;
}
