import { useState } from 'react';
import { CommerceClient } from './client';
import { useAllPages, useQuery } from './useQuery';
import type { Analytics, Category, Dispute, Page, ReportView } from './types';
import { ErrorBox, Pagination, Status } from './ui';
import { money, time } from './helpers';

type ListPage<T> = Page<T>&{total?:number};
function more<T>(page?:ListPage<T>){return page?.has_more??(page?.total!==undefined&&page.offset+page.items.length<page.total);}
export function ReportTarget({client,type,id,label}: {client:CommerceClient;type:string;id:string;label:string}) {
    const [reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[saved,setSaved]=useState(false);
    return <details className="report-target"><summary>{label}</summary><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError(undefined);try{await client.request('/customer/reports','POST',{target_type:type,target_id:id,reason});setSaved(true);}catch(e){setError(e);}finally{setBusy(false);}}}><label>举报原因<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||saved}>提交举报</button>{saved&&<p role="status">举报已记录，可在“举报与争议”查看处理结果。</p>}<ErrorBox error={error}/></form></details>;
}
export function CustomerCases({client}: {client:CommerceClient}) {return <><h1>举报与争议</h1><CustomerReports client={client}/><Disputes client={client}/></>;}
function CustomerReports({client}: {client:CommerceClient}) {const [offset,setOffset]=useState(0),q=useQuery<ListPage<ReportView>>(client,`/customer/reports?limit=20&offset=${offset}`);return <section className="panel"><div className="section-head"><h2>我的举报</h2><button className="subtle" onClick={q.refresh}>刷新举报</button></div><ErrorBox error={q.error}/>{q.loading&&<p>正在读取举报…</p>}{q.data?.items.map(r=><article className="review-card" key={r.id}><Status value={r.state}/><small>{r.target_type} · {r.target_id} · {time(r.created_at)}</small><p>{r.reason}</p>{r.decision_reason&&<p>处理说明：{r.decision_reason}</p>}</article>)}{q.data?.items.length===0&&<p className="muted">暂无举报。</p>}<Pagination offset={offset} hasMore={more(q.data)} onChange={setOffset}/></section>;}
export function DisputeEligibility(props:{client:CommerceClient;orderId:string;caseId:string;version:number;onChange:()=>void}) {
    const q=useQuery<{can_dispute:boolean;dispute_open:boolean;reason:string|null}>(props.client,`/customer/orders/${props.orderId}/after-sales/${props.caseId}/dispute-eligibility`);
    return <><ErrorBox error={q.error}/>{q.data?.can_dispute&&<RequestDispute {...props}/>} {q.data?.dispute_open&&<p className="warning">平台争议正在处理中，相关售后及冲突发货已冻结。请在“举报与争议”补充证据或查看裁决。</p>}</>;
}
export function RequestDispute({client,orderId,caseId,version,onChange}: {client:CommerceClient;orderId:string;caseId:string;version:number;onChange:()=>void}) {const [reason,setReason]=useState(''),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false);return <details><summary>申请平台争议仲裁</summary><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError(undefined);try{await client.request(`/customer/orders/${orderId}/after-sales/${caseId}/dispute`,'POST',{expected_version:version,reason});onChange();}catch(e){setError(e);}finally{setBusy(false);}}}><p className="muted">平台重新审查原售后申请。争议期间冻结相关售后及冲突发货；不会自动退款或回库。</p><label>争议原因与证据<textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy}>提交争议申请</button><ErrorBox error={error}/></form></details>;}
export function Disputes({client,shop,platform=false}: {client:CommerceClient;shop?:string;platform?:boolean}) {const [offset,setOffset]=useState(0),base=platform?'/platform/disputes':shop?`/merchant/shops/${shop}/disputes`:'/customer/disputes',q=useQuery<ListPage<Dispute>>(client,`${base}?limit=20&offset=${offset}`);return <section><div className="section-head"><h2>{platform?'争议仲裁':'售后争议'}</h2><button className="subtle" onClick={q.refresh}>刷新争议</button></div><ErrorBox error={q.error}/>{q.loading&&<p>正在读取争议…</p>}{q.data?.items.map(d=><DisputeCard key={`${d.id}-${d.version}`} client={client} d={d} base={base} merchant={!!shop} platform={platform} onChange={q.refresh}/>)}{q.data?.items.length===0&&<div className="empty">暂无争议。</div>}<Pagination offset={offset} hasMore={more(q.data)} onChange={setOffset}/></section>;}
function DisputeCard({client,d,base,merchant,platform,onChange}: {client:CommerceClient;d:Dispute;base:string;merchant:boolean;platform:boolean;onChange:()=>void}) {
    const [body,setBody]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false);
    const context=useQuery<DisputeContext>(client,`/platform/disputes/${d.id}/context`,platform);
    async function act(suffix:string,payload:object){setBusy(true);setError(undefined);try{await client.request(`${base}/${d.id}${suffix}`,'POST',{expected_version:d.version,...payload});onChange();}catch(e){setError(e);}finally{setBusy(false);}}
    return <article className="case-card panel" data-testid="dispute-case" data-dispute-id={d.id}><div className="section-head"><h3>售后争议 {d.id.slice(0,8)}</h3><Status value={d.state}/></div><small>订单 {d.order_id} · 售后 {d.case_id} · 版本 {d.version}</small><p>申请理由：{d.reason}</p><p>客户证据：{d.customer_evidence||'暂无补充'}</p><p>商家证据：{d.merchant_evidence||'暂无补充'}</p>{d.decision_reason&&<p>平台裁决说明：{d.decision_reason}</p>}<ErrorBox error={error}/>{platform&&<><ErrorBox error={context.error}/>{context.loading?<p>正在读取原售后与实际支付事实…</p>:context.data&&<DisputeFacts context={context.data}/>}</>}{d.state==='OPEN'&&!platform&&<><form onSubmit={e=>{e.preventDefault();act('/evidence',{body});}}><label>{merchant?'商家补充证据':'客户补充证据'}<textarea required maxLength={2000} value={body} onChange={e=>setBody(e.target.value)}/></label><button disabled={busy}>提交补充证据</button></form>{!merchant&&<button className="subtle" disabled={busy} onClick={()=>act('/withdraw',{})}>撤回争议</button>}</>}{d.state==='OPEN'&&platform&&<form onSubmit={e=>e.preventDefault()}><label>平台裁决理由<textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="button-row"><button disabled={busy||!reason.trim()||!context.data} onClick={()=>act('/decision',{decision:'APPROVE',reason})}>支持原售后申请</button><button className="subtle" disabled={busy||!reason.trim()||!context.data} onClick={()=>act('/decision',{decision:'UPHOLD',reason})}>维持商家决定</button></div><p className="muted">支持申请后仍按退款 / 退货流程办理。退款需独立模拟结果，退货需确认实物收回。</p></form>}{platform&&d.state==='OVERTURNED'&&d.can_refund&&<button disabled={busy} onClick={()=>act('/refunds',{})}>发起仲裁获准的模拟退款</button>}</article>;
}
interface DisputeContext {case_type:string;state:string;reason:string;merchant_decision_reason:string|null;requested_amount_minor:number;currency:string;financial_status:string;paid_minor:number;refunded_minor:number;return_state:string|null;lines:{title:string;quantity:number;unit_price_minor:number;shipped_qty:number;refunded_unshipped_qty:number;refunded_shipped_qty:number}[]}
function DisputeFacts({context:c}: {context:DisputeContext}) {return <section className="dispute-facts"><h4>原售后申请与金额事实</h4><p>{c.case_type==='UNSHIPPED_REFUND'?'未发货退款':'退货退款'} · <Status value={c.state}/></p><div className="detail-facts"><div>原申请金额<strong>{money(c.requested_amount_minor)}</strong></div><div>已成功支付<strong>{money(c.paid_minor)}</strong></div><div>已成功退款<strong>{money(c.refunded_minor)}</strong></div></div><p>原售后原因：{c.reason}</p><p>商家原审核说明：{c.merchant_decision_reason??'暂无审核说明'}</p><p>财务状态：<Status value={c.financial_status}/>{c.return_state?` · 退货状态 ${c.return_state}`:''}</p><div className="table-wrap"><table><thead><tr><th>申请商品</th><th>原单价</th><th>申请数量</th><th>已发数量</th><th>已退数量（未发 / 已发）</th></tr></thead><tbody>{c.lines.map((line,i)=><tr key={i}><td>{line.title}</td><td>{money(line.unit_price_minor)}</td><td>{line.quantity}</td><td>{line.shipped_qty}</td><td>{line.refunded_unshipped_qty} / {line.refunded_shipped_qty}</td></tr>)}</tbody></table></div><p className="muted">裁决只支持原申请数量与金额；服务端在提交时重新核对余额、发货和退货窗口。</p></section>;}
export function AnalyticsPanel({client,shop}: {client:CommerceClient;shop?:string}) {
    const [dates]=useState(()=>({today:new Date().toISOString().slice(0,10),tomorrow:new Date(Date.now()+86400000).toISOString().slice(0,10)}));
    const [start,setStart]=useState(dates.today.slice(0,8)+'01'),[end,setEnd]=useState(dates.tomorrow),[shopFilter,setShopFilter]=useState('');
    const [offset,setOffset]=useState(0);
    const [range,setRange]=useState({start:dates.today.slice(0,8)+'01T00:00:00Z',end:dates.tomorrow+'T00:00:00Z',shop:''});
    const q=useQuery<Analytics>(client,`${shop?`/merchant/shops/${shop}`:'/platform'}/analytics?start=${encodeURIComponent(range.start)}&end=${encodeURIComponent(range.end)}${range.shop?`&shop_id=${encodeURIComponent(range.shop)}`:''}&offset=${offset}&limit=20`),shops=useAllPages<{id:string;name:string}>(client,'/platform/shops',!shop);
    const a=q.data;
    return <section><div className="section-head"><h2>经营报表</h2><button className="subtle" onClick={q.refresh}>刷新报表</button></div><p className="simulation">模拟交易 · CNY · 成功支付 / 退款事实 · UTC [开始, 结束)</p><form className="filters" onSubmit={e=>{e.preventDefault();setOffset(0);setRange({start:start+'T00:00:00Z',end:end+'T00:00:00Z',shop:shopFilter});}}><label>开始日期（UTC）<input required type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>结束日期（不含）<input required type="date" min={start} value={end} onChange={e=>setEnd(e.target.value)}/></label>{!shop&&<label>报表店铺<select value={shopFilter} onChange={e=>setShopFilter(e.target.value)}><option value="">全部店铺</option>{shops.items.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<button>读取报表</button></form><ErrorBox error={q.error}/>{q.loading&&<p>正在汇总业务记录…</p>}{a&&<><div className="metrics">{[['支付总额',money(a.payment_total_minor)],['退款总额',money(a.refund_total_minor)],['净收款',money(a.net_total_minor)],['区间创建订单',a.orders_created],['区间完成订单',a.orders_completed]].map(([title,value])=><article key={title}><span>{title}</span><strong>{value}</strong></article>)}</div><p className="muted">净收款 = 成功支付 − 成功退款；此指标不代表利润或银行结算。</p><h3>当前积压</h3><div className="metrics">{[['未付款',a.backlog.unpaid],['待发货',a.backlog.awaiting_shipment],['运输中',a.backlog.in_transit],['售后待处理',a.backlog.after_sales]].map(([title,value])=><article key={title}><span>{title}</span><strong>{value}</strong></article>)}</div><DataTable title="每日交易" rows={a.daily}/><DataTable title="店铺汇总" rows={a.shops}/><DataTable title="商品实购与退款数量" rows={a.sales}/><Pagination offset={offset} hasMore={a.shops_has_more||a.sales_has_more} onChange={setOffset}/></>}</section>;
}
const columnLabels:Record<string,string>={date:'日期',day:'日期',shop_id:'店铺编号',shop_name:'店铺',product_id:'商品编号',title:'商品',sku_id:'SKU',payment_total_minor:'成功支付（分）',refund_total_minor:'成功退款（分）',net_total_minor:'净收款（分）',quantity:'实购数量',purchased_quantity:'实购数量',refunded_quantity:'退款数量',refunded_unshipped_quantity:'未发退款数量',refunded_shipped_quantity:'已发退款数量',orders_created:'创建订单',orders_completed:'完成订单'};
function DataTable({title,rows}: {title:string;rows:Record<string,string|number>[]}){const columns=Array.from(new Set(rows.flatMap(r=>Object.keys(r))));return <section className="report-table"><h3>{title}</h3>{rows.length?<div className="table-wrap"><table><thead><tr>{columns.map(k=><th key={k}>{columnLabels[k]??k}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{columns.map(k=><td key={k}>{row[k]}</td>)}</tr>)}</tbody></table></div>:<p className="muted">所选区间暂无记录。</p>}</section>;}

type Resource='accounts'|'shops'|'products'|'reviews'|'reports'|'categories'|'actions';
interface RecordView {id:string;version:number;username?:string;name?:string;title?:string;body?:string;active?:boolean;status?:string;state?:string;reason?:string;target_type?:string;target_id?:string;decision_reason?:string|null;shop_id?:string;visible?:boolean;moderation_hidden?:boolean;action?:string;actor_id?:string;created_at?:string}
const resourceLabels:Record<Resource,string>={accounts:'账户',shops:'店铺',products:'商品',reviews:'评价',reports:'举报与违规',categories:'商品分类',actions:'处理历史'};
export function PlatformWorkbench({client}: {client:CommerceClient}) {const [tab,setTab]=useState<Resource|'analytics'|'disputes'>('analytics');return <><span className="eyebrow">PLATFORM OPERATIONS / 独立平台权限</span><h1>平台运营工作台</h1><div className="workbench-tabs"><button className={tab==='analytics'?'active':''} onClick={()=>setTab('analytics')}>总览与报表</button>{(Object.keys(resourceLabels) as Resource[]).map(key=><button className={tab===key?'active':''} key={key} onClick={()=>setTab(key)}>{resourceLabels[key]}</button>)}<button className={tab==='disputes'?'active':''} onClick={()=>setTab('disputes')}>争议仲裁</button></div><div key={tab}>{tab==='analytics'?<AnalyticsPanel client={client}/>:tab==='disputes'?<Disputes client={client} platform/>:<PlatformList client={client} resource={tab}/>}</div></>;}
function PlatformList({client,resource}: {client:CommerceClient;resource:Resource}) {const [offset,setOffset]=useState(0),q=useQuery<ListPage<RecordView>>(client,`/platform/${resource}?limit=20&offset=${offset}`);return <><div className="section-head"><h2>{resourceLabels[resource]}</h2><button className="subtle" onClick={q.refresh}>刷新{resourceLabels[resource]}</button></div><ErrorBox error={q.error}/>{resource==='categories'&&<CategoryEditor client={client} onChange={q.refresh}/>} {q.loading&&<p>正在读取平台记录…</p>}{q.data?.items.map(r=>resource==='categories'?<CategoryEditor key={`${r.id}-${r.version}`} client={client} category={r as Category} onChange={q.refresh}/>:<ModerationRecord key={`${r.id}-${r.version}`} client={client} resource={resource} record={r} onChange={q.refresh}/>)}{q.data?.items.length===0&&<div className="empty">暂无记录。</div>}<Pagination offset={offset} hasMore={more(q.data)} onChange={setOffset}/></>;}
function CategoryEditor({client,category:c,onChange}: {client:CommerceClient;category?:Category;onChange:()=>void}) {const [name,setName]=useState(c?.name??''),[active,setActive]=useState(c?.active??true),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();return <form className="panel" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await client.request(c?`/platform/categories/${c.id}/edit`:'/platform/categories','POST',{...(c?{expected_version:c.version}:{}),name,active});if(!c)setName('');onChange();}catch(e){setError(e);}finally{setBusy(false);}}}><h3>{c?'维护分类':'创建分类'}</h3><label>分类名称<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>启用分类</label><button disabled={busy}>{c?'保存分类':'创建分类'}</button><ErrorBox error={error}/></form>;}
function ModerationRecord({client,resource,record:r,onChange}: {client:CommerceClient;resource:Exclude<Resource,'categories'>;record:RecordView;onChange:()=>void}) {
    const [reason,setReason]=useState(''),[action,setAction]=useState('WARN'),[decision,setDecision]=useState('RESOLVE'),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false);
    const target=(resource==='reports'||resource==='actions')?r.target_type:resource==='accounts'?'ACCOUNT':resource==='shops'?'SHOP':resource==='products'?'PRODUCT':'REVIEW';
    const actions=target==='ACCOUNT'?['WARN','SUSPEND_ACCOUNT','RESTORE_ACCOUNT']:target==='SHOP'?['WARN','SUSPEND_SHOP','RESTORE_SHOP']:target==='PRODUCT'?['WARN','HIDE_PRODUCT','RESTORE_PRODUCT']:['WARN','HIDE_REVIEW','RESTORE_REVIEW'];
    return <article className="panel moderation-record"><div className="section-head"><h3>{r.title??r.name??r.username??`${resourceLabels[resource]} ${r.id.slice(0,8)}`}</h3><Status value={(r.moderation_hidden?'HIDDEN':undefined)??r.status??r.state??(r.active===false?'SUSPENDED':r.visible===false?'HIDDEN':'ACTIVE')}/></div><small>记录 {r.id} · 版本 {r.version}{r.shop_id?` · 店铺 ${r.shop_id}`:''}</small>{r.action&&<p>处理动作：{actionLabels[r.action]??r.action} · {r.created_at?time(r.created_at):''}</p>}{r.actor_id&&<small>平台处理人 {r.actor_id}</small>}{r.body&&<p>{r.body}</p>}{r.reason&&<p>{resource==='actions'?'处理理由':'举报理由'}：{r.reason}</p>}{r.target_id&&<small>目标 {target} · {r.target_id}</small>}{r.decision_reason&&<p>处理说明：{r.decision_reason}</p>}<ErrorBox error={error}/>{resource!=='actions'&&(resource!=='reports'||r.state==='OPEN')&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError(undefined);try{await client.request(resource==='reports'?`/platform/reports/${r.id}/decision`:'/platform/moderation','POST',resource==='reports'?{expected_version:r.version,decision,action:decision==='DISMISS'?null:action,reason}:{target_type:target,target_id:r.id,expected_version:r.version,action,reason});onChange();}catch(e){setError(e);}finally{setBusy(false);}}}><div className="field-grid">{resource==='reports'&&<label>举报决定<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="RESOLVE">处理并结案</option><option value="DISMISS">驳回举报</option></select></label>}<label>平台处理动作<select value={action} onChange={e=>setAction(e.target.value)} disabled={decision==='DISMISS'}>{actions.map(value=><option key={value} value={value}>{actionLabels[value]??value}</option>)}</select></label></div><label>处理理由<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason.trim()}>保存平台处理决定</button></form>}</article>;
}
const actionLabels:Record<string,string>={WARN:'警告并保留处理记录',HIDE_PRODUCT:'隐藏违规商品',RESTORE_PRODUCT:'恢复商品公开展示',HIDE_REVIEW:'隐藏违规评价',RESTORE_REVIEW:'恢复评价展示',SUSPEND_SHOP:'暂停店铺新交易',RESTORE_SHOP:'恢复店铺',SUSPEND_ACCOUNT:'停用普通账户',RESTORE_ACCOUNT:'恢复普通账户'};
