import { useEffect, useState } from 'react';
import { ApiError, CommerceClient } from './client';
import { useAllPages, useQuery } from './useQuery';
import type { Category, Favorite, Order, Page, ProductCardView, ProductImage, Review } from './types';
import { ErrorBox, Pagination } from './ui';
import { time } from './helpers';
import { ReportTarget } from './Platform';

export function Photo({client,image}: {client:CommerceClient;image:ProductImage}) {
    const [url,setUrl]=useState('');
    useEffect(()=>{let active=true,objectUrl=''; client.imageBlob(image.url).then(blob=>{objectUrl=URL.createObjectURL(blob);if(active)setUrl(objectUrl);else URL.revokeObjectURL(objectUrl);}).catch(()=>{});return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[client,image.url]);
    return url?<img className="product-photo" src={url} alt={image.alt||'商品图片'}/>:<div className="photo-empty">图片暂未载入</div>;
}
export function FavoriteButton({client,productId,onChange,initial=false}: {client:CommerceClient;productId:string;onChange?:()=>void;initial?:boolean}) {
    const [active,setActive]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();
    return <><button className="subtle" disabled={busy} aria-pressed={active} onClick={async()=>{setBusy(true);setError(undefined);try{await client.request('/customer/favorites','POST',{product_id:productId,active:!active});setActive(!active);onChange?.();}catch(e){setError(e);}finally{setBusy(false);}}}>{active?'取消收藏':'收藏商品'} ♡</button><ErrorBox error={error}/></>;
}
export function ProductDetails({client,product,customer}: {client:CommerceClient;product:ProductCardView;customer:boolean}) {
    const [open,setOpen]=useState(false);
    return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary>商品详情与购买评价 · {product.review_count??0} 条</summary>{open&&<><div className="image-gallery">{product.images?.map(image=><Photo key={image.id} client={client} image={image}/>)}</div><p>{product.category_name??'未分类'} · {product.rating===null?'暂无评分':`${product.rating} / 5`}</p><Reviews client={client} path={`/shopping/products/${product.id}/reviews`} reportAllowed={customer}/>{customer&&<><ReportTarget client={client} type="PRODUCT" id={product.id} label="举报商品"/><ReportTarget client={client} type="SHOP" id={product.shop_id} label="举报店铺"/></>}</>}</details>;
}
export function Reviews({client,path,merchant=false,reportAllowed=false}: {client:CommerceClient;path:string;merchant?:boolean;reportAllowed?:boolean}) {
    const [offset,setOffset]=useState(0),q=useQuery<Page<Review>>(client,`${path}?limit=20&offset=${offset}`);
    return <><ErrorBox error={q.error}/>{q.loading&&<p>正在读取购买评价…</p>}{q.data?.items.map(r=><ReviewCard key={`${r.id}-${r.version}`} client={client} review={r} reportAllowed={reportAllowed} onChange={q.refresh} replyPath={merchant?`${path}/${r.id}/reply`:undefined}/>)}{q.data?.items.length===0&&<p className="muted">暂无购买评价。</p>}<Pagination offset={offset} hasMore={q.data?.has_more??false} onChange={setOffset}/><button className="subtle" onClick={q.refresh}>刷新评价</button></>;
}
function ReviewCard({client,review:r,replyPath,onChange,reportAllowed}: {client:CommerceClient;review:Review;replyPath?:string;onChange:()=>void;reportAllowed:boolean}) {
    const [body,setBody]=useState(r.reply??''),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false),[reply,setReply]=useState(r.reply);
    return <article className="review-card"><strong>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)} · 已验证购买</strong><small>{time(r.created_at)} · 购买财务状态 {r.financial_status}</small><p>{r.body}</p>{reply&&<blockquote>商家回复：{reply}</blockquote>}{replyPath&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const updated=await client.request<Review>(replyPath,'POST',{expected_version:r.version,body});setReply(updated.reply);onChange();}catch(e){setError(e);}finally{setBusy(false);}}}><label>商家评价回复<textarea required maxLength={2000} value={body} onChange={e=>setBody(e.target.value)}/></label><button disabled={busy}>保存评价回复</button></form>}{reportAllowed&&<ReportTarget client={client} type="REVIEW" id={r.id} label="举报评价"/>}<ErrorBox error={error}/></article>;
}
export function Favorites({client}: {client:CommerceClient}) {
    const [offset,setOffset]=useState(0),q=useQuery<Page<Favorite>>(client,`/customer/favorites?limit=20&offset=${offset}`);
    return <><div className="section-head"><h1>我的收藏</h1><button className="subtle" onClick={q.refresh}>刷新收藏</button></div><ErrorBox error={q.error}/>{q.loading&&<p>正在读取收藏…</p>}<div className="products">{q.data?.items.map(f=><article className="product" key={f.id}>{f.product?.images[0]&&<Photo client={client} image={f.product.images[0]}/>}<div className="product-body"><h3>{f.product?.title??'商品已不可公开读取'}</h3><p>{f.purchasable?'当前可购买':'当前不可购买'}</p><RemoveFavorite client={client} id={f.product_id} onChange={q.refresh}/>{f.product&&<ProductDetails client={client} product={f.product} customer/>}</div></article>)}</div>{q.data?.items.length===0&&<div className="empty">还没有收藏。选物时收藏喜欢的商品。</div>}<Pagination offset={offset} hasMore={q.data?.has_more??false} onChange={setOffset}/></>;
}
function RemoveFavorite({client,id,onChange}: {client:CommerceClient;id:string;onChange:()=>void}) {const [error,setError]=useState<unknown>(),[busy,setBusy]=useState(false);return <><button className="subtle" disabled={busy} onClick={async()=>{setBusy(true);try{await client.request('/customer/favorites','POST',{product_id:id,active:false});onChange();}catch(e){setError(e);}finally{setBusy(false);}}}>移除收藏</button><ErrorBox error={error}/></>;}
export function PurchaseReviews({client,order}: {client:CommerceClient;order:Order}) {return <section className="panel"><h3>我的购买评价</h3><p className="muted">每条已完成订单商品可评价一次；已保存的评价可以继续编辑。</p>{order.lines?.map(line=><PurchaseReview key={line.id} client={client} orderId={order.id} lineId={line.id} title={line.title}/>)}</section>;}
function PurchaseReview({client,orderId,lineId,title}: {client:CommerceClient;orderId:string;lineId:string;title:string}) {
    const [rating,setRating]=useState(5),[body,setBody]=useState(''),[review,setReview]=useState<Review>(),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
    useEffect(()=>{let active=true;client.request<Review>(`/customer/orders/${orderId}/lines/${lineId}/review`).then(r=>{if(active){setReview(r);setRating(r.rating);setBody(r.body);setLoading(false);}}).catch(e=>{if(active){if(!(e instanceof ApiError&&e.status===404))setError(e);setLoading(false);}});return()=>{active=false;};},[client,orderId,lineId]);
    return <form className="review-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError(undefined);try{setReview(await client.request<Review>(review?`/customer/reviews/${review.id}/edit`:`/customer/orders/${orderId}/lines/${lineId}/review`,'POST',{...(review?{expected_version:review.version}:{}),rating,body}));}catch(e){setError(e);}finally{setBusy(false);}}}><h4>{title}</h4>{loading&&<p>正在读取已保存评价…</p>}<label>购买评分<select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} 星</option>)}</select></label><label>购买评价内容<textarea required maxLength={2000} value={body} onChange={e=>setBody(e.target.value)}/></label><button disabled={busy||loading||!!error}>{review?'保存评价修改':'提交购买评价'}</button>{review&&<p role="status">评价已保存 · 版本 {review.version}{!review.visible?' · 已被平台隐藏':''}</p>}<ErrorBox error={error}/></form>;
}
export function ProductExperience({client,path,onChange}: {client:CommerceClient;path:string;onChange:()=>void}) {
    const q=useQuery<ProductCardView>(client,path+'/experience'),categories=useAllPages<Category>(client,'/shopping/categories'),[error,setError]=useState<unknown>(),[busy,setBusy]=useState(false),[file,setFile]=useState<File>(),[alt,setAlt]=useState('');
    async function action(suffix:string,body:unknown){setBusy(true);setError(undefined);try{await client.request(path+'/experience'+suffix,'POST',body);q.refresh();onChange();}catch(e){setError(e);}finally{setBusy(false);}}
    const p=q.data;
    return <section className="sku-panel"><h3>图片与分类</h3><ErrorBox error={error??q.error??categories.error}/>{p&&<><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action('',{expected_version:p.version,category_id:f.get('category')||null});}}><label>商品分类<select aria-label="商品分类" name="category" defaultValue={p.category_id??''} key={p.version}><option value="">未分类</option>{categories.items.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button disabled={busy}>保存商品分类</button></form><div className="image-gallery">{p.images.map(image=><div key={image.id}><Photo client={client} image={image}/><button className="subtle" disabled={busy} onClick={()=>action(`/images/${image.id}/delete`,{expected_version:p.version})}>删除图片</button></div>)}</div><form onSubmit={async e=>{e.preventDefault();if(!file)return;setError(undefined);if(file.size>3*1024*1024){setError(new Error('图片原始文件不能超过 3 MiB'));return;}try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});await action('/images',{expected_version:p.version,data_base64:data,alt});}catch(e){setError(e);}}}><label>上传商品图片<input type="file" accept="image/png,image/jpeg,image/webp" required onChange={e=>setFile(e.target.files?.[0])}/></label><label>图片说明<input maxLength={200} value={alt} onChange={e=>setAlt(e.target.value)}/></label><p className="muted">PNG / JPEG / WebP · 单张最多 3 MiB · 每件商品最多 8 张。服务端检查并去除图片元数据。</p><button disabled={busy||p.images.length>=8}>上传图片</button></form></>}</section>;
}
