"""Freeze the Core MVP Product schema, independent of future ORM changes."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_core_mvp"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("code", name=op.f("uq_teams_code")),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "AGENT",
                "SUPERVISOR",
                "ADMIN",
                name="role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(role = 'ADMIN' AND team_id IS NULL) OR (role IN ('AGENT', 'SUPERVISOR') AND "
            "team_id IS NOT NULL)",
            name=op.f("ck_users_role_team"),
        ),
        sa.CheckConstraint("username ~ '^[A-Za-z0-9._-]{3,64}$'", name=op.f("ck_users_username")),
        sa.CheckConstraint("lock_version > 0", name=op.f("ck_users_lock_version")),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_users_team_id_teams"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "token_digest ~ '^[0-9a-f]{64}$'", name=op.f("ck_auth_sessions_token_digest")
        ),
        sa.CheckConstraint("expires_at > created_at", name=op.f("ck_auth_sessions_expiry")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_sessions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("token_digest", name=op.f("uq_auth_sessions_token_digest")),
    )
    op.create_table(
        "inquiries",
        sa.Column("source_system", sa.Text(), nullable=False),
        sa.Column("external_inquiry_id", sa.Text(), nullable=False),
        sa.Column("external_order_id", sa.Text(), nullable=True),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_agent_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "OPEN",
                "CONTEXT_READY",
                "DRAFTED",
                "APPROVED",
                "ESCALATED",
                name="state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("escalation_reason", sa.Text(), nullable=True),
        sa.Column("latest_run_id", sa.Uuid(), nullable=True),
        sa.Column("current_context_id", sa.Uuid(), nullable=True),
        sa.Column("current_draft_id", sa.Uuid(), nullable=True),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(state = 'ESCALATED' AND escalation_reason IS NOT NULL AND "
            "btrim(escalation_reason) <> '') OR (state <> 'ESCALATED' AND "
            "escalation_reason IS NULL)",
            name=op.f("ck_inquiries_escalation_reason"),
        ),
        sa.CheckConstraint(
            "btrim(external_inquiry_id) <> ''", name=op.f("ck_inquiries_external_inquiry_id")
        ),
        sa.CheckConstraint(
            "external_order_id IS NULL OR btrim(external_order_id) <> ''",
            name=op.f("ck_inquiries_external_order_id"),
        ),
        sa.CheckConstraint("lock_version > 0", name=op.f("ck_inquiries_lock_version")),
        sa.ForeignKeyConstraint(
            ["assigned_agent_id"],
            ["users.id"],
            name=op.f("fk_inquiries_assigned_agent_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_inquiries_team_id_teams"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inquiries")),
        sa.UniqueConstraint(
            "source_system",
            "external_inquiry_id",
            name=op.f("uq_inquiries_source_system_external_inquiry_id"),
        ),
    )
    op.create_table(
        "audit_logs",
        sa.Column("inquiry_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "LOGIN_SUCCESS",
                "LOGIN_FAILED",
                "LOGOUT",
                "ACCESS_DENIED",
                "RESOLVE_STARTED",
                "RESOLVE_SUCCEEDED",
                "RESOLVE_PARTIAL",
                "RESOLVE_FAILED",
                "GENERATION_STARTED",
                "GENERATION_SUCCEEDED",
                "GENERATION_FAILED",
                "DRAFT_EDITED",
                "VALIDATION_PASSED",
                "VALIDATION_FAILED",
                "APPROVED",
                "ESCALATED",
                "OPERATION_RECOVERED",
                name="event_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("record_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("safe_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inquiry_id"],
            ["inquiries.id"],
            name=op.f("fk_audit_logs_inquiry_id_inquiries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "resolution_runs",
        sa.Column("inquiry_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "RUNNING",
                "SUCCEEDED",
                "PARTIAL",
                "FAILED",
                name="state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(state = 'RUNNING' AND finished_at IS NULL) OR (state <> 'RUNNING' AND "
            "finished_at IS NOT NULL)",
            name=op.f("ck_resolution_runs_finished_at"),
        ),
        sa.CheckConstraint(
            "btrim(idempotency_key) <> ''", name=op.f("ck_resolution_runs_idempotency_key")
        ),
        sa.CheckConstraint(
            "request_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_resolution_runs_request_hash")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_resolution_runs_version")),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_resolution_runs_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inquiry_id"],
            ["inquiries.id"],
            name=op.f("fk_resolution_runs_inquiry_id_inquiries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resolution_runs")),
        sa.UniqueConstraint(
            "inquiry_id",
            "idempotency_key",
            name=op.f("uq_resolution_runs_inquiry_id_idempotency_key"),
        ),
        sa.UniqueConstraint(
            "inquiry_id", "version", name=op.f("uq_resolution_runs_inquiry_id_version")
        ),
    )
    op.create_table(
        "context_versions",
        sa.Column("inquiry_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Text(), nullable=False),
        sa.Column("policy_version", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "quality",
            sa.Enum(
                "COMPLETE", "DEGRADED", name="quality", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("version > 0", name=op.f("ck_context_versions_version")),
        sa.ForeignKeyConstraint(
            ["inquiry_id"],
            ["inquiries.id"],
            name=op.f("fk_context_versions_inquiry_id_inquiries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["resolution_runs.id"],
            name=op.f("fk_context_versions_run_id_resolution_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_context_versions")),
        sa.UniqueConstraint(
            "inquiry_id", "version", name=op.f("uq_context_versions_inquiry_id_version")
        ),
        sa.UniqueConstraint("run_id", name=op.f("uq_context_versions_run_id")),
    )
    op.create_table(
        "source_fetches",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "operation",
            sa.Enum(
                "get_inquiry",
                "get_order",
                "get_parcels",
                "get_shipment",
                "get_notes",
                name="operation",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("target_id", sa.Text(), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "SUCCESS",
                "EMPTY",
                "NOT_FOUND",
                "NO_TRACKING",
                "TIMEOUT",
                "UNAVAILABLE",
                "INVALID_RESPONSE",
                "REJECTED",
                "CONFLICT",
                name="outcome",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("source_system", sa.Text(), nullable=False),
        sa.Column(
            "canonical_payload",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(outcome IN ('SUCCESS', 'EMPTY') AND canonical_payload IS NOT NULL AND "
            "fetched_at IS NOT NULL AND error_code IS NULL) OR (outcome NOT IN "
            "('SUCCESS', 'EMPTY') AND canonical_payload IS NULL AND fetched_at IS NULL "
            "AND error_code IS NOT NULL)",
            name=op.f("ck_source_fetches_outcome_payload"),
        ),
        sa.CheckConstraint(
            "canonical_payload IS NULL OR (jsonb_typeof(canonical_payload) = 'object' AND "
            "canonical_payload ? 'records' AND jsonb_typeof(canonical_payload->'records') "
            "= 'array')",
            name=op.f("ck_source_fetches_records"),
        ),
        sa.CheckConstraint(
            "outcome <> 'EMPTY' OR (operation IN ('get_parcels', 'get_notes') AND "
            "canonical_payload->'records' = '[]'::jsonb)",
            name=op.f("ck_source_fetches_empty_result"),
        ),
        sa.CheckConstraint(
            "outcome <> 'SUCCESS' OR canonical_payload->'records' <> '[]'::jsonb",
            name=op.f("ck_source_fetches_nonempty_success"),
        ),
        sa.CheckConstraint("completed_at >= started_at", name=op.f("ck_source_fetches_time_order")),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["resolution_runs.id"],
            name=op.f("fk_source_fetches_run_id_resolution_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_fetches")),
        sa.UniqueConstraint(
            "run_id",
            "operation",
            "target_id",
            name=op.f("uq_source_fetches_run_id_operation_target_id"),
        ),
    )
    op.create_table(
        "generation_attempts",
        sa.Column("inquiry_id", sa.Uuid(), nullable=False),
        sa.Column("context_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                name="state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column(
            "analysis", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "model_metadata",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(state = 'RUNNING' AND finished_at IS NULL) OR (state <> 'RUNNING' AND "
            "finished_at IS NOT NULL)",
            name=op.f("ck_generation_attempts_finished_at"),
        ),
        sa.CheckConstraint(
            "btrim(idempotency_key) <> ''", name=op.f("ck_generation_attempts_idempotency_key")
        ),
        sa.CheckConstraint(
            "request_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_generation_attempts_request_hash")
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_generation_attempts_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["context_versions.id"],
            name=op.f("fk_generation_attempts_context_id_context_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inquiry_id"],
            ["inquiries.id"],
            name=op.f("fk_generation_attempts_inquiry_id_inquiries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_attempts")),
        sa.UniqueConstraint(
            "inquiry_id",
            "idempotency_key",
            name=op.f("uq_generation_attempts_inquiry_id_idempotency_key"),
        ),
    )
    op.create_table(
        "draft_revisions",
        sa.Column("inquiry_id", sa.Uuid(), nullable=False),
        sa.Column("context_id", sa.Uuid(), nullable=False),
        sa.Column("generation_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("parent_revision_id", sa.Uuid(), nullable=True),
        sa.Column("editor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "origin",
            sa.Enum("AI", "HUMAN", name="origin", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reply_text", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(origin = 'AI' AND generation_attempt_id IS NOT NULL AND editor_id IS NULL) "
            "OR (origin = 'HUMAN' AND editor_id IS NOT NULL AND parent_revision_id IS NOT "
            "NULL)",
            name=op.f("ck_draft_revisions_origin_author"),
        ),
        sa.CheckConstraint(
            "length(reply_text) BETWEEN 1 AND 10000 AND btrim(reply_text) <> ''",
            name=op.f("ck_draft_revisions_reply_text"),
        ),
        sa.CheckConstraint(
            "text_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_draft_revisions_text_hash")
        ),
        sa.CheckConstraint("revision > 0", name=op.f("ck_draft_revisions_revision")),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["context_versions.id"],
            name=op.f("fk_draft_revisions_context_id_context_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["editor_id"],
            ["users.id"],
            name=op.f("fk_draft_revisions_editor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["generation_attempt_id"],
            ["generation_attempts.id"],
            name=op.f("fk_draft_revisions_generation_attempt_id_generation_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inquiry_id"],
            ["inquiries.id"],
            name=op.f("fk_draft_revisions_inquiry_id_inquiries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_revision_id"],
            ["draft_revisions.id"],
            name=op.f("fk_draft_revisions_parent_revision_id_draft_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_draft_revisions")),
        sa.UniqueConstraint(
            "inquiry_id", "revision", name=op.f("uq_draft_revisions_inquiry_id_revision")
        ),
    )
    op.create_table(
        "validation_results",
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("context_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version", sa.Text(), nullable=False),
        sa.Column("validator_version", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PASS", "FAIL", name="status", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "text_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_validation_results_text_hash")
        ),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["context_versions.id"],
            name=op.f("fk_validation_results_context_id_context_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["draft_revisions.id"],
            name=op.f("fk_validation_results_draft_id_draft_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validation_results")),
    )
    op.create_table(
        "approvals",
        sa.Column("inquiry_id", sa.Uuid(), nullable=False),
        sa.Column("context_id", sa.Uuid(), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("validation_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "btrim(idempotency_key) <> ''", name=op.f("ck_approvals_idempotency_key")
        ),
        sa.CheckConstraint(
            "request_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_approvals_request_hash")
        ),
        sa.CheckConstraint("text_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_approvals_text_hash")),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["context_versions.id"],
            name=op.f("fk_approvals_context_id_context_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["draft_revisions.id"],
            name=op.f("fk_approvals_draft_id_draft_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inquiry_id"],
            ["inquiries.id"],
            name=op.f("fk_approvals_inquiry_id_inquiries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_approvals_reviewer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["validation_id"],
            ["validation_results.id"],
            name=op.f("fk_approvals_validation_id_validation_results"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint(
            "inquiry_id", "idempotency_key", name=op.f("uq_approvals_inquiry_id_idempotency_key")
        ),
        sa.UniqueConstraint("inquiry_id", name=op.f("uq_approvals_inquiry_id")),
    )
    op.create_foreign_key(
        op.f("fk_inquiries_current_draft_id_draft_revisions"),
        "inquiries",
        "draft_revisions",
        ["current_draft_id"],
        ["id"],
        ondelete="RESTRICT",
        use_alter=True,
    )
    op.create_foreign_key(
        op.f("fk_inquiries_latest_run_id_resolution_runs"),
        "inquiries",
        "resolution_runs",
        ["latest_run_id"],
        ["id"],
        ondelete="RESTRICT",
        use_alter=True,
    )
    op.create_foreign_key(
        op.f("fk_inquiries_current_context_id_context_versions"),
        "inquiries",
        "context_versions",
        ["current_context_id"],
        ["id"],
        ondelete="RESTRICT",
        use_alter=True,
    )
    # ### end Alembic commands ###
    op.execute("""
        CREATE FUNCTION product_immutable_record() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'Product historical records are append-only' USING ERRCODE = '23514';
        END; $$
    """)
    op.execute(
        "CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON source_fetches "
        "FOR EACH ROW EXECUTE FUNCTION product_immutable_record()"
    )
    op.execute(
        "CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON context_versions "
        "FOR EACH ROW EXECUTE FUNCTION product_immutable_record()"
    )
    op.execute(
        "CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON draft_revisions "
        "FOR EACH ROW EXECUTE FUNCTION product_immutable_record()"
    )
    op.execute(
        "CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON validation_results "
        "FOR EACH ROW EXECUTE FUNCTION product_immutable_record()"
    )
    op.execute(
        "CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON approvals "
        "FOR EACH ROW EXECUTE FUNCTION product_immutable_record()"
    )
    op.execute(
        "CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON audit_logs "
        "FOR EACH ROW EXECUTE FUNCTION product_immutable_record()"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_inquiries_current_context_id_context_versions"), "inquiries", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_inquiries_latest_run_id_resolution_runs"), "inquiries", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_inquiries_current_draft_id_draft_revisions"), "inquiries", type_="foreignkey"
    )
    op.drop_table("approvals")
    op.drop_table("validation_results")
    op.drop_table("draft_revisions")
    op.drop_table("generation_attempts")
    op.drop_table("source_fetches")
    op.drop_table("context_versions")
    op.drop_table("resolution_runs")
    op.drop_table("audit_logs")
    op.drop_table("inquiries")
    op.drop_table("auth_sessions")
    op.drop_table("users")
    op.drop_table("teams")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION product_immutable_record()")
